from __future__ import annotations

import re
from pathlib import Path


_GENERIC_TITLE_RE = re.compile(
    r"^(?:(?:ai|codex|claude(?: code)?|opencode)?\s*session(?:\s*[·:#-]\s*[\w-]+)?|"
    r"untitled session|new session(?:\s*[-·:].*)?)$",
    re.IGNORECASE,
)
_NOISE_MARKERS = (
    "request_user_input availability",
    "<apps_instructions>",
    "<collaboration_mode>",
    "<environment_context>",
    "<permissions instructions>",
    "<plugins_instructions>",
    "<skills_instructions>",
    "available skills",
    "filesystem sandboxing",
    "you are codex",
    "the following is the codex agent history",
    "the messages below were generated by",
    "suggestion mode: suggest what the user",
    "the user interrupted the previous turn",
    "at the start of your turn",
    "all agents in the team",
    "child agents can also spawn",
    "they may be addressed as to=/root",
    "collaboration tools cannot be called from inside",
    "# agents.md instructions",
    "permanent repository rules for codex",
    "read agents.md",
    "technical communication",
    "working with the user",
    "autonomy and persistence",
    "destructive actions",
    "clarity: you communicate reasoning",
    "continue working toward the active thread goal",
    "escalation requests",
)
_GENERIC_TOPIC_KEYS = {
    "continue",
    "continue working toward the active thread goal",
    "go ahead",
    "good",
    "hello",
    "hi",
    "hi there",
    "make pr",
    "make prs",
    "next",
    "okay",
    "read agents",
    "thanks",
    "thank you",
    "untitled session",
    "warmup",
    "work on",
    "values",
    "clarity you communicate reasoning explicitly and",
    "escalation",
}
_LEADING_REQUEST_RE = re.compile(
    r"^(?:/goal\s+|now\s+|please\s+|can you\s+|could you\s+|would you\s+|"
    r"i (?:now )?want you to\s+|i need you to\s+|help me(?: to)?\s+|go ahead and\s+|"
    r"work on\s+)",
    re.IGNORECASE,
)
_CONTINUATION_CONTROLS = {
    "carry on",
    "continue",
    "continue please",
    "go ahead",
    "go ahead now",
    "go on",
    "keep going",
    "next",
    "now continue",
    "okay continue",
    "please continue",
    "proceed",
    "resume",
    "yes continue",
}
_CONTINUATION_SENTENCE_RE = re.compile(
    r"^continue if you have (?:any )?next steps(?: or stop and ask for clarification "
    r"if you are unsure how to proceed)?$",
    re.IGNORECASE,
)
_CONTINUATION_STATE_RE = re.compile(
    r"^(?:please )?(?:continue|resume)(?: the task)? from "
    r"(?:the )?(?:latest|last|current) state$",
    re.IGNORECASE,
)
_CONTINUATION_THREAD_RE = re.compile(
    r"^(?:continue|resume)\s*:\s*"
    r"[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)
_CONTINUATION_THREAD_LINE_RE = re.compile(
    r"(?im)^\s*(?:continue|resume)\s*:\s*"
    r"[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}\s*$",
)
_EXPLICIT_TASK_ACTION_RE = re.compile(
    r"\b(?:add|build|change|create|debug|diagnose|fix|implement|investigate|"
    r"make|remove|repair|replace|run|ship|test|update|verify|write)\b",
    re.IGNORECASE,
)
_NON_TASK_REACTION_RE = re.compile(
    r"\b(?:"
    r"(?:i\s+(?:think\s+)?)?give\s+up|"
    r"(?:are|r)\s+(?:you|u)\s+(?:fucking\s+)?kidding\s+me|"
    r"(?:you(?:'re|\s+are)|u\s+r|ur)\s+(?:fucking\s+)?useless|"
    r"(?:piece|picec)\s+of\s+(?:shit|shite)"
    r")\b",
    re.IGNORECASE,
)
_TASK_METADATA_KEYS = frozenset({
    "clientthreadid",
    "conversationid",
    "hostid",
    "projectid",
    "sessionid",
    "sourcedocumentid",
    "sourcethreadid",
    "threadid",
    "turnid",
    "workspaceid",
})
_TASK_METADATA_IDENTIFIER_RE = re.compile(
    r"^(?:[a-z][A-Za-z0-9]*(?:Id|ID|Uuid|UUID|Url|URL)|"
    r"[a-z][a-z0-9_]*(?:_id|_uuid|_url))$",
)
_ATTACHMENT_FILE_RE = re.compile(
    r"^(?:screenshot\s+\d{4}-\d{2}-\d{2}\s+at\s+\d{1,2}(?:[.:]\d{2}){0,2}|"
    r"codex-clipboard-[a-z0-9-]+)(?:\.png|\.jpe?g|\.webp)?(?::.*)?$",
    re.IGNORECASE,
)
_COMMAND_ONLY_RE = re.compile(
    r"^/(?:model|help|compact|resume|status|clear|reset|init)(?:\s+.*)?$",
    re.IGNORECASE,
)
_TOOL_TRANSCRIPT_REQUEST_RE = re.compile(
    r"^\s*called the [a-z0-9_.:-]+ tool with the following input\s*:",
    re.IGNORECASE,
)
_CONTEXT_PACK_FILE_PAYLOAD_RE = re.compile(
    r"^\s*<path>[\s\S]*?context-engine-harness-[^<]*[/\\]"
    r"context-pack\.md</path>\s*<type>file</type>\s*<content>",
    re.IGNORECASE,
)
_HARNESS_CONTINUATION_MESSAGE_RE = re.compile(
    r"^\s*[\"']?continue the task using the attached context engine context "
    r"pack\.\s*verify the current repository state before editing\.?[\"']?\s*$",
    re.IGNORECASE,
)
_CORRECTION_PATTERNS = (
    re.compile(r"\bstill\s+(?:displayed|showing|visible|there|broken|wrong|not\b)", re.IGNORECASE),
    re.compile(r"\bwhat did (?:you|u) (?:remove|change|fix|do)\b", re.IGNORECASE),
    re.compile(r"\b(?:isn't|isnt|wasn't|wasnt|didn't|didnt|doesn't|doesnt|not)\s+(?:fixed|removed|working|changed|gone|implemented)\b", re.IGNORECASE),
    re.compile(r"\byou (?:said|claimed).{0,120}\bbut\b", re.IGNORECASE),
    re.compile(r"\b(?:not actually|misunderstanding|incorrect|wrong result|does not match|doesn't match|didnt match)\b", re.IGNORECASE),
)
_TOPIC_SIGNAL_WORDS = (
    "attention",
    "banner",
    "broken",
    "duplicate",
    "evidence",
    "issue",
    "session",
    "text",
    "topic",
    "ui",
    "wrong",
)


def is_internal_session_content(content: str | None) -> bool:
    """Return True for harness-generated assessment sessions, not user work."""

    user_turns = re.findall(
        r"(?ms)^\[USER\]\n(.*?)(?=^\[[A-Z_]+\]\n|\Z)",
        content or "",
    )
    # Internal review prompts appear at the start of their own session. Looking
    # only at the opening user turns prevents a normal fork from being hidden
    # merely because its copied history later mentions an assessment transcript.
    lowered = "\n".join(user_turns[:3]).lower()
    return (
        "the following is the codex agent history whose request action you are assessing"
        in lowered
        and ">>> transcript start" in lowered
    )


def clean_session_message_text(value: str | None) -> str:
    """Remove attachment transport markup while preserving the user's request."""

    text = re.sub(r"(?is)<image\b.*?</image>", " ", value or "")
    text = re.sub(
        r"\[([^\]]+)\]\((?:/Users|/var|/private)/[^)]+\)",
        r"\1",
        text,
    )
    lines: list[str] = []
    for raw_line in text.splitlines():
        stripped = raw_line.strip()
        plain = re.sub(r"^[#>*\-\d.)\s]+", "", stripped).strip()
        lowered = plain.lower()
        if not plain:
            if lines and lines[-1]:
                lines.append("")
            continue
        if lowered in {"files mentioned by the user:", "my request for codex:"}:
            continue
        if lowered.startswith((
            "referenced chatgpt conversation:",
            "this is untrusted",
        )):
            continue
        if _is_referenced_conversation_payload(stripped):
            continue
        if _ATTACHMENT_FILE_RE.fullmatch(plain):
            continue
        if (
            ("/var/folders/" in stripped or "/temporaryitems/" in lowered)
            and re.search(r"\.(?:png|jpe?g|webp)(?:[\"'>:]|$)", stripped, re.IGNORECASE)
        ):
            continue
        if lowered.startswith(("image name=", "path=", "[image #")):
            continue
        lines.append(raw_line.rstrip())
    return re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip()


def derive_session_attention_items(
    content: str | None,
    *,
    max_items: int = 3,
) -> list[dict[str, str | int]]:
    """Find explicit user corrections after an agent result without using AI."""

    turns = re.findall(
        r"(?ms)^\[([A-Z_ -]+)\]\s*(.*?)(?=^\[[A-Z_ -]+\]\s*|\Z)",
        content or "",
    )
    assistant_seen = False
    items: list[dict[str, str | int]] = []
    seen: set[str] = set()
    last_user_index = max(
        (
            index
            for index, (raw_role, _) in enumerate(turns)
            if raw_role.strip().lower() in {"user", "human", "you"}
        ),
        default=-1,
    )
    for turn_index, (raw_role, raw_text) in enumerate(turns):
        role = raw_role.strip().lower()
        if role in {"assistant", "ai", "codex", "claude", "opencode", "gpt"}:
            assistant_seen = True
            continue
        if role not in {"user", "human", "you"} or not assistant_seen:
            continue
        display = clean_session_message_text(raw_text)
        compact = re.sub(r"\s+", " ", display).strip()
        if not compact or not any(pattern.search(compact) for pattern in _CORRECTION_PATTERNS):
            continue
        topic = _shorten(_clean_candidate(raw_text), max_words=10, max_chars=72)
        key = _topic_key(topic or compact)
        if not key or key in seen:
            continue
        seen.add(key)
        items.append({
            "kind": "user_correction",
            "title": topic or "User reported a mismatch with the visible result",
            "summary": compact[:280].rstrip(),
            "attention_score": 90,
            "temporal_status": (
                "current" if turn_index == last_user_index else "previous"
            ),
        })
    return items[-max_items:]


def derive_session_topic(
    content: str | None,
    *,
    explicit_title: str | None = None,
    tool: str | None = None,
    session_id: str | None = None,
) -> str | None:
    """Return a short human topic, never a provider name or raw session ID."""

    title = _clean_candidate(explicit_title or "")
    if (
        title
        and not is_task_identifier_noise(explicit_title)
        and not is_task_identifier_noise(title)
        and not _is_generic_title(title, tool=tool, session_id=session_id)
        and not _looks_like_bootstrap_noise(title)
    ):
        return _shorten(title)

    text = content or ""
    user_blocks = re.findall(
        r"(?ms)^\[USER\]\s*(.*?)(?=^\[[A-Z_]+\]\s*|\Z)",
        text,
    )
    for candidate in user_blocks or [text]:
        if _looks_like_bootstrap_noise(candidate):
            continue
        normalized_request = normalize_substantive_user_request(candidate)
        if not normalized_request:
            continue
        cleaned = _clean_candidate(normalized_request)
        if cleaned and _topic_key(cleaned) not in _GENERIC_TOPIC_KEYS:
            return _shorten(cleaned)
    return None


def derive_session_topics(
    content: str | None,
    *,
    explicit_title: str | None = None,
    cwd: str | None = None,
    tool: str | None = None,
    session_id: str | None = None,
    max_topics: int = 6,
) -> list[str]:
    """Return distinct, human-readable subjects discussed in a session.

    A session is deliberately allowed to have several topics. The provider title
    remains the best first signal, while later user turns capture topic changes
    inside a long-running conversation. A repository directory is included as a
    project anchor when it is meaningful.
    """

    if max_topics <= 0:
        return []

    candidates: list[str] = []
    primary = derive_session_topic(
        content,
        explicit_title=explicit_title,
        tool=tool,
        session_id=session_id,
    )
    if primary:
        candidates.append(primary)

    project_name = _project_name_from_cwd(cwd)
    if project_name:
        candidates.append(project_name)

    text = content or ""
    user_blocks = re.findall(
        r"(?ms)^\[(?:USER|HUMAN|YOU)\]\s*(.*?)(?=^\[[A-Z_ -]+\]\s*|\Z)",
        text,
    )
    for block in user_blocks:
        if _looks_like_bootstrap_noise(block):
            continue
        normalized_request = normalize_substantive_user_request(block)
        if not normalized_request:
            continue
        cleaned = _clean_candidate(normalized_request)
        if cleaned:
            candidates.append(_shorten(cleaned, max_words=10, max_chars=72))

    topics: list[str] = []
    seen: set[str] = set()
    for candidate in candidates:
        normalized = _topic_key(candidate)
        if not normalized or normalized in _GENERIC_TOPIC_KEYS or normalized in seen:
            continue
        seen.add(normalized)
        topics.append(candidate)
        if len(topics) >= max_topics:
            break
    return topics


def derive_latest_session_topic(
    content: str | None,
    *,
    explicit_title: str | None = None,
    tool: str | None = None,
    session_id: str | None = None,
) -> str | None:
    """Return the newest meaningful user topic in a session."""

    text = content or ""
    user_blocks = re.findall(
        r"(?ms)^\[(?:USER|HUMAN|YOU)\]\s*(.*?)(?=^\[[A-Z_ -]+\]\s*|\Z)",
        text,
    )
    for block in reversed(user_blocks):
        if _looks_like_bootstrap_noise(block):
            continue
        normalized_request = normalize_substantive_user_request(block)
        if not normalized_request:
            continue
        cleaned = _clean_candidate(normalized_request)
        normalized = _topic_key(cleaned)
        if cleaned and normalized and normalized not in _GENERIC_TOPIC_KEYS:
            return _shorten(cleaned, max_words=10, max_chars=72)
    return derive_session_topic(
        content,
        explicit_title=explicit_title,
        tool=tool,
        session_id=session_id,
    )


def _is_generic_title(title: str, *, tool: str | None, session_id: str | None) -> bool:
    if (
        not title
        or _GENERIC_TITLE_RE.fullmatch(title)
        or _topic_key(title) in _GENERIC_TOPIC_KEYS
    ):
        return True
    lowered = title.lower()
    if session_id and session_id.lower() in lowered:
        return True
    short_id = (session_id or "")[-12:].lower()
    if short_id and short_id in lowered:
        return True
    return bool(tool and lowered in {tool.lower(), f"{tool.lower()} session"})


def _looks_like_bootstrap_noise(value: str) -> bool:
    lowered = value.lower()
    return any(marker in lowered for marker in _NOISE_MARKERS)


def is_session_instruction_noise(value: str | None) -> bool:
    """Return whether transcript text is agent-runtime guidance, not user work."""

    return bool(value and _looks_like_bootstrap_noise(value))


def is_continuation_control(value: str | None) -> bool:
    """Return whether a user turn controls continuation without defining new work."""

    normalized = re.sub(r"[^a-z0-9']+", " ", str(value or "").lower()).strip()
    return bool(
        normalized in _CONTINUATION_CONTROLS
        or _CONTINUATION_SENTENCE_RE.fullmatch(normalized)
        or _CONTINUATION_STATE_RE.fullmatch(normalized)
        or _CONTINUATION_THREAD_RE.fullmatch(str(value or "").strip())
    )


def is_task_identifier_noise(value: str | None) -> bool:
    """Return whether text is a transport/schema identifier, not user work."""

    text = str(value or "").strip()
    if not text:
        return False
    if _is_referenced_conversation_payload(text):
        return True
    candidate = text.strip(" \t\r\n{}[]()\"'`:;,")
    if not candidate or re.search(r"\s", candidate):
        return False
    normalized = re.sub(r"[^a-z0-9_]+", "", candidate.casefold())
    return (
        normalized in _TASK_METADATA_KEYS
        or bool(_TASK_METADATA_IDENTIFIER_RE.fullmatch(candidate))
    )


def normalize_substantive_user_request(value: str | None) -> str | None:
    """Return executable user work without attachment or continuation transport."""

    text = clean_session_message_text(value)
    if (
        len(text) < 4
        or _TOOL_TRANSCRIPT_REQUEST_RE.match(text)
        or _CONTEXT_PACK_FILE_PAYLOAD_RE.match(text)
        or _HARNESS_CONTINUATION_MESSAGE_RE.fullmatch(text)
        or is_session_instruction_noise(text)
        or is_continuation_control(text)
        or is_task_identifier_noise(text)
    ):
        return None
    reaction_candidate = _CONTINUATION_THREAD_LINE_RE.sub(" ", text)
    reaction_candidate = re.sub(r"\s+", " ", reaction_candidate).strip()
    if (
        reaction_candidate
        and _NON_TASK_REACTION_RE.search(reaction_candidate)
        and not _EXPLICIT_TASK_ACTION_RE.search(reaction_candidate)
    ):
        # A correction or emotional reaction remains useful session evidence,
        # but it must not replace the earlier executable request.
        return None
    return text


def is_substantive_user_request(value: str | None) -> bool:
    """Accept user work only when it is neither runtime policy nor a control turn."""

    return normalize_substantive_user_request(value) is not None


def extract_delegated_user_request(value: str | None) -> str | None:
    """Extract the user-owned task sentence from a Codex delegation envelope."""

    text = str(value or "")
    if "<codex_delegation" not in text.lower():
        return None
    match = re.search(r"<input>([\s\S]*?)</input>", text, re.IGNORECASE)
    if not match:
        return None
    for paragraph in re.split(r"\n\s*\n", match.group(1).strip()):
        candidate = re.sub(r"\s+", " ", paragraph).strip()
        normalized = normalize_substantive_user_request(candidate)
        if normalized:
            return normalized
    return None


def _project_name_from_cwd(cwd: str | None) -> str | None:
    if not cwd:
        return None
    path = Path(cwd).expanduser()
    name = path.name.strip()
    if path.parent.name.lower() in {"home", "users"}:
        return None
    if not name or name.lower() in {"home", "users", "desktop", "workspace", "tmp", "private"}:
        return None
    cleaned = re.sub(r"[-_]+", " ", name)
    return _shorten(cleaned, max_words=6, max_chars=48)


def _topic_key(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", value.lower()).strip()


def _clean_candidate(value: str) -> str:
    text = clean_session_message_text(value)
    if _COMMAND_ONLY_RE.fullmatch(text.strip()):
        return ""
    text = re.sub(r"```.*?```", " ", text, flags=re.DOTALL)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"https?://\S+", " ", text)
    text = re.sub(r"(?:/[\w. -]+){2,}", " ", text)
    text = re.sub(
        r"\b[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}\b",
        " ",
        text,
        flags=re.IGNORECASE,
    )
    lines = []
    for raw_line in text.splitlines():
        line = re.sub(r"^[#>*\-\d.)\s]+", "", raw_line).strip()
        if not line or line.startswith("["):
            continue
        if line.lower().startswith(("files mentioned", "image #")):
            continue
        if _COMMAND_ONLY_RE.fullmatch(line):
            continue
        if any(marker in line.lower() for marker in _NOISE_MARKERS):
            continue
        lines.append(line)
    if not lines:
        return ""
    joined = " ".join(lines)
    clauses = [item.strip() for item in re.split(r"[.!?;,]+", joined) if item.strip()]
    if not clauses:
        return ""
    sentence = clauses[0]
    if re.match(
        r"^(?:wait\b|what did\b|nope\b|but\b|also\b|i see\b|refer to (?:the )?(?:screenshot|image|file)\b)",
        sentence,
        re.IGNORECASE,
    ):
        sentence = max(clauses[1:] or clauses, key=_clause_topic_score)
    previous = None
    while sentence and sentence != previous:
        previous = sentence
        sentence = _LEADING_REQUEST_RE.sub("", sentence).strip()
    sentence = re.sub(r"\ba\s+oss\b", "an OSS", sentence, flags=re.IGNORECASE)
    sentence = re.sub(r"\boss\s+sucess\b", "OSS success", sentence, flags=re.IGNORECASE)
    if (
        "topic" in sentence.lower()
        and "screenshot" in sentence.lower()
        and any(marker in sentence.lower() for marker in ("actual", "instead", "not helpful", "misunderstan"))
    ):
        sentence = "Use the discussion topic instead of screenshot filenames"
    replacements = {
        r"\bi\b": "I",
        r"\bu\b": "you",
        r"\bdidnt\b": "didn't",
        r"\bdispalyed\b": "displayed",
        r"\bseesion\b": "session",
    }
    for pattern, replacement in replacements.items():
        sentence = re.sub(pattern, replacement, sentence, flags=re.IGNORECASE)
    sentence = re.sub(r"\s+", " ", sentence).strip(" :;,-")
    return "" if is_task_identifier_noise(sentence) else sentence


def _is_referenced_conversation_payload(value: str) -> bool:
    text = str(value or "").strip()
    if not text.startswith(("{", "[")):
        return False
    lowered = text.casefold()
    return (
        bool(re.search(r"[\"']conversationid[\"']\s*:", lowered))
        and bool(re.search(r"[\"']conversation[\"']\s*:", lowered))
    )


def _clause_topic_score(value: str) -> tuple[int, int]:
    lowered = value.lower()
    signals = sum(1 for word in _TOPIC_SIGNAL_WORDS if re.search(rf"\b{word}\b", lowered))
    return signals, min(len(value), 160)


def _shorten(value: str, max_words: int = 7, max_chars: int = 56) -> str:
    words = value.split()
    shortened = " ".join(words[:max_words]).strip()
    truncated = len(words) > max_words
    if len(shortened) > max_chars:
        shortened = shortened[:max_chars].rsplit(" ", 1)[0]
        truncated = True
    if shortened and truncated:
        shortened = f"{shortened.rstrip(' ,;:-')}..."
    return shortened[:1].upper() + shortened[1:] if shortened else ""
